### ISSUE TITLE
Issue with Stream Cipher

### ISSUE THREAD

**Issue by jayko8899** [jbainbridge98/cipherApp#3]
![debug_img](https://user-images.githubusercontent.com/73153981/144757361-2f851ad9-043e-4bcd-bb19-a9c057f0017b.png)

Message: he.llo,!
Decrypted: he.llo,

Encryption / Decryption for stream cipher did not work properly as shown in image

**Comment by bloated-david** [comment]
<img width="1381" alt="Screen Shot 2021-12-05 at 4 12 56 PM" src="https://user-images.githubusercontent.com/54128926/144764161-f2216700-6e4f-447c-a9cd-71b4d8e36c8a.png">

Hey it looks like you messed the 7th bit, it works for me.

**Comment by jayko8899** [comment]
You're 100% right. My mistake

**Comment by bloated-david** [comment]
ur good we gotta get them points

**Comment by symxmyz233** [comment]
**It is not a bug**
