### ISSUE TITLE
Stream cipher problem

### ISSUE THREAD

**Issue by DolphinLHT** [jbainbridge98/cipherApp#6]
![bug3](https://user-images.githubusercontent.com/56650412/144775918-559e204d-7966-4d50-bc0f-7458495ba0a1.png)

**Comment by bloated-david** [comment]
<img width="1357" alt="Screen Shot 2021-12-05 at 11 41 42 PM" src="https://user-images.githubusercontent.com/54128926/144788668-2942a57f-19e8-42ec-ade9-f623244ef8f4.png">

**Comment by bloated-david** [comment]
If you look at your ciphertext that was outputted from the encryption there's a trapezoid symbol which became a square for the generated plaintext. That usually means your computer doesn't have that font symbol I think. Maybe you have an old computer or windows. Like TA Wensen said about the bug being reimplemented by others, I don't think this applies as a bug

**Comment by symxmyz233** [comment]
**It is not a bug.**
